from datetime import datetime, timezone
from typing import Optional

from pydantic import BaseModel

__all__ = ["Source", "SourcePublic"]


class Source(BaseModel):
    id: str
    format: Optional[str] = None
    # The filename that was provided by the user. The value None indicates that the source was
    # generated by the system as a container to hold multiple other sources.
    filename: Optional[str] = None
    created_at: datetime = datetime.now(timezone.utc)


class SourcePublic(Source):
    pass
